print("=== Receipt Printer ===", end="\n\n")

store_name = input("Store name: ")
item_name = input("Item name: ")
quantity = input("Quantity: ")
price = input("Price per item: ")
customer_name = input("Customer name: ")

print()
print("=" * 30)
print("           " + store_name)
print("=" * 30)
print()
print("Customer: " + customer_name)
print()
print(item_name)
print("  " + quantity + " x $" + price)
print()
print("-" * 30)
print("  Total items: " + quantity)
print("=" * 30)
print("    Thank you for your purchase!")
print("=" * 30)
